name: x0D0D0P

on: [push, workflow_dispatch]

jobs:
  build:
 #   runs-on: ubuntu-latest
    runs-on: kali-linux
    steps:
#---------------------------------------------------preparation
    - name: whoami
      run: sudo whoami
      
    - name: hostname
      run: hostname 
    - name: version
      run: sudo lsb_release -a
      
  #  - name: adduser
  #    run: sudo adduser x
    
    - name: whoami x
      run: whoami
    - name: whoami root
      run: sudo whoami
      
    - name: updateF
      run: sudo apt update
#---------------------------------------------------x0R0R0R
    - name: x0R0R0R install 
      run: sudo apt install xrdp
    - name: x0R0R0R activate 
      run: sudo systemctl enable xrdp
    - name: P0OR0T open 
      run: sudo ufw allow from any to any port 3389 proto tcp
   #---------------------------------------------------N0G0R0O0K
    - name: N0J0R0Ok install 
      run: sudo snap install ngrok --devmode
    - name: N0J0R0Ok AUTH 
      run: sudo ngrok authtoken 1tKuOSxi2qkXJh2O3VrKmYlSi4t_2BQ9W6dyHsaefEkLhuGbk
    - name: N0J0R0Ok R0D0P
      run: sudo ngrok tcp 3389
